SIGNAL(aida_time_subsys, aida.ts.subsystem_id, DATA12);
SIGNAL(aida_time_t1, aida.ts.t1, DATA16);
SIGNAL(aida_time_t2, aida.ts.t2, DATA16);
SIGNAL(aida_time_t3, aida.ts.t3, DATA16);
SIGNAL(aida_time_t4, aida.ts.t4, DATA16);
SIGNAL(aida_TsH_1, aida.subev.ts_high, DATA32);
//SIGNAL(NO_INDEX_LIST: aida_TsH_10000);
SIGNAL(aida_TsM_1, aida.subev.ts_med, DATA32);
//SIGNAL(NO_INDEX_LIST: aida_TsM_10000);
SIGNAL(aida_TsL_1, aida.subev.ts_low, DATA32);
//SIGNAL(NO_INDEX_LIST: aida_TsL_10000);
SIGNAL(aida_Module_1, aida.subev.module, DATA8);
//SIGNAL(NO_INDEX_LIST: aida_Module_10000);
SIGNAL(aida_Channel_1, aida.subev.channel, DATA8);
//SIGNAL(NO_INDEX_LIST: aida_Channel_10000);
SIGNAL(aida_Adc_1, aida.subev.adc, DATA16);
//SIGNAL(NO_INDEX_LIST: aida_Adc_10000);
//SIGNAL(aida_energy, aida.subev.adc, );