#include "data_src.hh"
#include "dummy_external.hh"
#include "external_data.hh"
#include "zero_suppress.hh"
#include <iostream>
#include <fstream>
#include <sstream>
#include <map>
#include <limits>

DUMMY_EXTERNAL_MAP_STRUCT_FORW(EXT_REVERSE_BUFFER);

class EXT_REVERSE_BUFFER
{
    public:
        EXT_REVERSE_BUFFER();
        ~EXT_REVERSE_BUFFER();

        void __clean();
        EXT_DECL_UNPACK();

    public:
        DUMMY_EXTERNAL_DUMP(EXT_REVERSE_BUFFER);
        DUMMY_EXTERNAL_SHOW_MEMBERS(EXT_REVERSE_BUFFER);
        DUMMY_EXTERNAL_ENUMERATE_MEMBERS(EXT_REVERSE_BUFFER);
        DUMMY_EXTERNAL_ZERO_SUPPRESS_INFO_PTRS(EXT_REVERSE_BUFFER);


};

DUMMY_EXTERNAL_MAP_STRUCT(EXT_REVERSE_BUFFER);
DUMMY_EXTERNAL_WATCHER_STRUCT(EXT_REVERSE_BUFFER);
DUMMY_EXTERNAL_CORRELATION_STRUCT(EXT_REVERSE_BUFFER);
DUMMY_EXTERNAL_CALIB_MAP_STRUCT(EXT_REVERSE_BUFFER);